name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

  tests:
    name: Integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [14, 16, 18]
        exclude:
          - os: macos-latest
            node: 14
          - os: macos-latest
            node: 18
          - os: windows-latest
            node: 14
          - os: windows-latest
            node: 18
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run integration tests
        run: yarn test
