## This pipeline is needed till Snyk adds Yarn Berry support. See https://github.com/kachkaev/njt/pull/29#issuecomment-711438900

name: Dependency checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 6"

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run yarn npm audit
        run: yarn npm audit
